export const INDUSTRIES = [
  "Agriculture & Forestry",
  "Arts & Entertainment",
  "Automotive",
  "Aviation & Aerospace",
  "Banking & Financial Services",
  "Construction & Real Estate",
  "Consumer Goods",
  "Education & E-Learning",
  "Energy & Utilities",
  "Engineering",
  "E-commerce",
  "Fintech",
  "Food & Beverage",
  "Government & Public Administration",
  "Healthcare & Pharmaceuticals",
  "Hospitality & Tourism",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Media & Communications",
  "Mining & Metals",
  "Non-Profit & NGO",
  "Professional Services & Consulting",
  "Retail",
  "Tech & Software",
  "Telecommunications",
  "Transportation",
  "Other"
];
